# Generated by Django 4.0.6 on 2022-07-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School_name', models.CharField(max_length=100)),
                ('School_location', models.CharField(max_length=100)),
                ('School_principal', models.CharField(max_length=100)),
            ],
        ),
    ]
